# Generated by Django 5.2.12 on 2026-04-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OttoProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_reference', models.CharField(db_index=True, max_length=255, unique=True)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ean', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('pzn', models.CharField(blank=True, max_length=255, null=True)),
                ('mpn', models.CharField(blank=True, max_length=255, null=True)),
                ('moin', models.CharField(blank=True, max_length=255, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('product_description', models.JSONField(blank=True, default=dict)),
                ('media_assets', models.JSONField(blank=True, default=list)),
                ('order_data', models.JSONField(blank=True, default=dict)),
                ('pricing', models.JSONField(blank=True, default=dict)),
                ('logistics', models.JSONField(blank=True, default=dict)),
                ('compliance', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OTTO Product',
                'verbose_name_plural': 'OTTO Products',
                'ordering': ['-updated_at'],
            },
        ),
    ]
