# Generated by Django 5.2.13 on 2026-04-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otto_service', '0002_split_jv_xl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ottoproductjv',
            options={'ordering': ['-updated_at'], 'verbose_name': 'OTTO Product', 'verbose_name_plural': 'OTTO Products'},
        ),
        migrations.AlterModelOptions(
            name='ottoproductxl',
            options={'ordering': ['-updated_at'], 'verbose_name': 'OTTO Product', 'verbose_name_plural': 'OTTO Products'},
        ),
    ]
