# Generated by Django 5.2.14 on 2026-05-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ean", models.CharField(max_length=13)),
                ("controller", models.CharField(max_length=50)),
                ("storefront", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=1000)),
                ("id_product", models.CharField(max_length=50)),
                ("id_unit", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=16)),
                ("reference_price", models.CharField(max_length=16)),
            ],
        ),
    ]
