# Generated by Django 5.2.12 on 2026-04-08 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoodApiResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('success', models.BooleanField(default=False)),
                ('account', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ean', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('source_file_ignored', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hood API Response',
                'verbose_name_plural': 'Hood API Responses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='HoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('category_id', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=64, null=True)),
                ('item_mode', models.CharField(blank=True, max_length=64, null=True)),
                ('item_number', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('product_properties', models.JSONField(blank=True, default=list)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hood_service.hoodapiresponse')),
            ],
            options={
                'verbose_name': 'Hood Item',
                'verbose_name_plural': 'Hood Items',
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('response', 'item_id'), name='unique_hood_item_per_response')],
            },
        ),
    ]
