# Generated by Django 5.2.12 on 2026-04-08 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hood_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HoodApiResponse",
            new_name="HoodApiResponseJV",
        ),
        migrations.RenameModel(
            old_name="HoodItem",
            new_name="HoodItemJV",
        ),
        migrations.AlterModelOptions(
            name="hoodapiresponsejv",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Hood API Response JV",
                "verbose_name_plural": "Hood API Responses JV",
            },
        ),
        migrations.AlterModelOptions(
            name="hooditemjv",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Hood Item JV",
                "verbose_name_plural": "Hood Items JV",
            },
        ),
        migrations.AlterField(
            model_name="hooditemjv",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_jv",
                to="hood_service.hoodapiresponsejv",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="hooditemjv",
            name="unique_hood_item_per_response",
        ),
        migrations.AddConstraint(
            model_name="hooditemjv",
            constraint=models.UniqueConstraint(
                fields=("response", "item_id"),
                name="unique_hood_item_jv_per_response",
            ),
        ),
        migrations.CreateModel(
            name="HoodApiResponseXL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(blank=True, max_length=64, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("success", models.BooleanField(default=False)),
                ("account", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("ean", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("source_file_ignored", models.CharField(blank=True, max_length=255, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Hood API Response XL",
                "verbose_name_plural": "Hood API Responses XL",
            },
        ),
        migrations.CreateModel(
            name="HoodItemXL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_id", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("price", models.CharField(blank=True, max_length=255, null=True)),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("category_id", models.CharField(blank=True, max_length=255, null=True)),
                ("condition", models.CharField(blank=True, max_length=64, null=True)),
                ("item_mode", models.CharField(blank=True, max_length=64, null=True)),
                ("item_number", models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ("title", models.TextField(blank=True, null=True)),
                ("images", models.JSONField(blank=True, default=list)),
                ("product_properties", models.JSONField(blank=True, default=list)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items_xl",
                        to="hood_service.hoodapiresponsexl",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Hood Item XL",
                "verbose_name_plural": "Hood Items XL",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("response", "item_id"),
                        name="unique_hood_item_xl_per_response",
                    )
                ],
            },
        ),
    ]
