# Generated by Django 5.2.13 on 2026-04-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood_service', '0002_split_jv_xl'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoodapiresponsejv',
            name='external_push_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hoodapiresponsejv',
            name='external_push_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pushed', 'Pushed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='hoodapiresponsejv',
            name='local_save_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('saved', 'Saved'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='hoodapiresponsexl',
            name='external_push_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='hoodapiresponsexl',
            name='external_push_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pushed', 'Pushed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='hoodapiresponsexl',
            name='local_save_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('saved', 'Saved'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
    ]
