# Generated by Django 5.2.15 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hood_service", "0003_hoodapiresponsejv_external_push_error_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HoodProductSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account", models.CharField(max_length=16)),
                ("ean", models.CharField(max_length=255)),
                ("payload", models.JSONField(default=dict)),
                ("source_item_id", models.CharField(blank=True, default="", max_length=255)),
                ("saved_at", models.DateTimeField(auto_now=True)),
                ("restored_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-saved_at"]},
        ),
        migrations.AddConstraint(
            model_name="hoodproductsnapshot",
            constraint=models.UniqueConstraint(
                fields=("account", "ean"),
                name="unique_hood_product_snapshot_account_ean",
            ),
        ),
    ]
