# Generated by Django 5.2.13 on 2026-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jv_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedproduct',
            name='update_user',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='importedproduct',
            name='user_create',
            field=models.CharField(default='system', max_length=150),
        ),
    ]
