# Generated by Django 5.2.13 on 2026-04-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jv_services', '0002_importedproduct_update_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedproduct',
            name='local_save_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('saved', 'Saved'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='importedproduct',
            name='source_push_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='importedproduct',
            name='source_push_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pushed', 'Pushed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
    ]
