# Generated by Django 5.2.13 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jv_services", "0004_xljvbatchjob_xljvbatchjobitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedproduct",
            name="site_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=64),
        ),
        migrations.RemoveConstraint(
            model_name="importedproduct",
            name="uniq_imported_product_site_source_product_id",
        ),
        migrations.RemoveConstraint(
            model_name="importedproduct",
            name="uniq_imported_product_site_ean",
        ),
        migrations.AddConstraint(
            model_name="importedproduct",
            constraint=models.UniqueConstraint(
                fields=("site", "site_key", "source_product_id"),
                name="uniq_imported_product_site_site_key_source_product_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="importedproduct",
            constraint=models.UniqueConstraint(
                fields=("site", "site_key", "ean"),
                name="uniq_imported_product_site_site_key_ean",
            ),
        ),
    ]
