# Generated by Django 5.2.13 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jv_services", "0005_importedproduct_site_key_and_unique_per_sitekey"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedproductcategory",
            name="main_category",
            field=models.BooleanField(default=False),
        ),
    ]
