# Generated by Django 5.2.14 on 2026-05-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jv_services', '0010_alter_jvbatchjob_site_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jvbatchjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('applied', 'Applied'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
    ]
