# Generated by Django 6.0.3 on 2026-04-06 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_number', models.CharField(max_length=255, unique=True)),
                ('global_price', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=13)),
                ('title', models.TextField()),
                ('memo', models.TextField()),
                ('status', models.CharField(choices=[('paid', 'paid'), ('no_paid', 'no_paid')], default='no_paid', max_length=10)),
                ('date', models.DateTimeField()),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.kid')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kid', 'order_id'), name='unique_order_per_kid')],
            },
        ),
    ]
