# Generated by Django 5.2.12 on 2026-04-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_kid_global_price_alter_kid_id_alter_orders_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='global_price',
        ),
        migrations.AddField(
            model_name='kid',
            name='photo',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='kid',
            name='place',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='global_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
