# Generated by Django 5.2.12 on 2026-04-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_kid_global_price_kid_photo_kid_place_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
