# Generated by Django 5.2.12 on 2026-04-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_kid_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='kid',
            name='kid_number',
            field=models.CharField(max_length=255),
        ),
    ]
