# Generated by Django 5.2.12 on 2026-04-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_orders_quantity_alter_kid_kid_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='sku',
            field=models.TextField(blank=True, null=True),
        ),
    ]
