# Generated by Django 5.2.12 on 2026-04-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_orders_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='buyer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
