# Generated by Django 5.2.13 on 2026-04-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_orders_buyer_orders_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='additional_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
