# Generated by Django 5.2.13 on 2026-04-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_kid_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=128)),
                ('idem_key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('state', models.CharField(default='processing', max_length=32)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, default='', max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'idem_key'), name='uniq_idempotency_scope_key')],
            },
        ),
    ]
