# Generated by Django 5.2.14 on 2026-05-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0014_kid_room_type_listing_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eanpool",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="eanusage",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
