# Generated by Django 5.2.14 on 2026-06-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0017_productattributes_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productattributes",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
