# Generated by Django 5.2.15 on 2026-06-15 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_remove_kid_furniture_type_alter_eanpool_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='kid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='database.kid'),
        ),
        migrations.CreateModel(
            name='Ean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jv', models.CharField(blank=True, max_length=13, null=True)),
                ('xl', models.CharField(blank=True, max_length=13, null=True)),
                ('otto_jv', models.CharField(blank=True, max_length=13, null=True)),
                ('otto_xl', models.CharField(blank=True, max_length=13, null=True)),
                ('kaufland_jv', models.CharField(blank=True, max_length=13, null=True)),
                ('kaufland_xl', models.CharField(blank=True, max_length=13, null=True)),
                ('hood_jv', models.CharField(blank=True, max_length=13, null=True)),
                ('hood_xl', models.CharField(blank=True, max_length=13, null=True)),
                ('ebay_jv', models.CharField(blank=True, max_length=13, null=True)),
                ('ebay_xl', models.CharField(blank=True, max_length=13, null=True)),
                ('kid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ean_site', to='database.kid')),
            ],
        ),
    ]
