# Generated by Django 5.2.15 on 2026-06-23 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_productattributes_quantity_force_eur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='quantity',
        ),
    ]
