# Generated by Django 5.2.15 on 2026-06-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0027_remove_orders_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributes',
            name='company',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
