# Generated by Django 5.2.14 on 2026-06-23 11:20

from django.db import migrations, models


def _forward_normalize_kid_numbers(apps, schema_editor):
    Kid = apps.get_model("database", "Kid")
    db_alias = schema_editor.connection.alias
    for kid in Kid.objects.using(db_alias).all().iterator():
        value = kid.kid_number
        if value is None:
            normalized = []
        elif isinstance(value, str):
            normalized = [value.strip()] if value.strip() else []
        elif isinstance(value, (list, tuple, set)):
            normalized = []
            seen = set()
            for item in value:
                item_str = str(item or "").strip()
                if not item_str or item_str in seen:
                    continue
                seen.add(item_str)
                normalized.append(item_str)
        else:
            item_str = str(value).strip()
            normalized = [item_str] if item_str else []
        if value != normalized:
            kid.kid_number = normalized
            kid.save(using=db_alias, update_fields=["kid_number"])


def _backward_normalize_kid_numbers(apps, schema_editor):
    Kid = apps.get_model("database", "Kid")
    db_alias = schema_editor.connection.alias
    for kid in Kid.objects.using(db_alias).all().iterator():
        value = kid.kid_number
        if isinstance(value, list):
            normalized = str(value[0]).strip() if value else ""
        elif value is None:
            normalized = ""
        else:
            normalized = str(value).strip()
        if value != normalized:
            kid.kid_number = normalized
            kid.save(using=db_alias, update_fields=["kid_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_ean_main_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='kid_number',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(_forward_normalize_kid_numbers, _backward_normalize_kid_numbers),
    ]
