# Generated by Django 5.2.15 on 2026-06-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0030_alter_kid_kid_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='place',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
