# Generated by Django 5.2.15 on 2026-06-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_alter_kid_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='store',
            field=models.BooleanField(default=False),
        ),
    ]
