# Generated by Django 5.2.15 on 2026-06-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0031_alter_kid_place'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE database_kid
                    ADD COLUMN IF NOT EXISTS store boolean NOT NULL DEFAULT false
                    """,
                    reverse_sql="""
                    ALTER TABLE database_kid
                    DROP COLUMN IF EXISTS store
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='kid',
                    name='store',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
