# Generated by Django 5.2.15 on 2026-06-25 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0033_alter_ean_ebay_jv_alter_ean_ebay_xl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ean',
            name='kid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ean', to='database.kid'),
        ),
        migrations.CreateModel(
            name='EanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jv', models.BooleanField(default=False)),
                ('xl', models.BooleanField(default=False)),
                ('otto_jv', models.BooleanField(default=False)),
                ('otto_xl', models.BooleanField(default=False)),
                ('kaufland_jv', models.BooleanField(default=False)),
                ('kaufland_xl', models.BooleanField(default=False)),
                ('hood_jv', models.BooleanField(default=False)),
                ('hood_xl', models.BooleanField(default=False)),
                ('ebay_jv', models.BooleanField(default=False)),
                ('ebay_xl', models.BooleanField(default=False)),
                ('ean', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='database.kid')),
            ],
        ),
    ]
