# Generated by Django 5.2.15 on 2026-06-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_alter_ean_kid_eanstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
