# Generated by Django 5.2.15 on 2026-06-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0034_nullify_placeholder_eans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ean',
            name='jv',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
