# Generated by Django 5.2.15 on 2026-06-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0035_alter_ean_jv'),
        ('database', '0035_alter_kid_place'),
    ]

    operations = [
    ]
