# Generated by Django 6.0.0 on 2026-07-15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0039_remove_kid_listing_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryChangeLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kid_number", models.CharField(blank=True, default="", max_length=255)),
                ("place", models.CharField(blank=True, default="", max_length=255)),
                ("actor_login", models.CharField(blank=True, default="", max_length=255)),
                ("actor_name", models.CharField(blank=True, default="", max_length=255)),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("changes", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("kid", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="change_logs", to="database.kid")),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
