# Generated by Django 6.0.0 on 2026-07-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0040_inventory_change_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("afterbuy_user_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("afterbuy_user_id_alt", models.CharField(blank=True, default="", max_length=255)),
                ("user_id_platform", models.CharField(blank=True, default="", max_length=255)),
                ("billing_first_name", models.CharField(blank=True, default="", max_length=255)),
                ("billing_last_name", models.CharField(blank=True, default="", max_length=255)),
                ("billing_title", models.CharField(blank=True, default="", max_length=255)),
                ("billing_company", models.CharField(blank=True, default="", max_length=255)),
                ("billing_street", models.CharField(blank=True, default="", max_length=255)),
                ("billing_street_2", models.CharField(blank=True, default="", max_length=255)),
                ("billing_postal_code", models.CharField(blank=True, default="", max_length=32)),
                ("billing_city", models.CharField(blank=True, default="", max_length=255)),
                ("billing_state_or_province", models.CharField(blank=True, default="", max_length=255)),
                ("billing_country", models.CharField(blank=True, default="", max_length=255)),
                ("billing_country_iso", models.CharField(blank=True, default="", max_length=8)),
                ("billing_phone", models.CharField(blank=True, default="", max_length=128)),
                ("billing_fax", models.CharField(blank=True, default="", max_length=128)),
                ("billing_email", models.CharField(blank=True, default="", max_length=320)),
                ("billing_is_merchant", models.BooleanField(default=False)),
                ("billing_tax_id_number", models.CharField(blank=True, default="", max_length=255)),
                ("shipping_first_name", models.CharField(blank=True, default="", max_length=255)),
                ("shipping_last_name", models.CharField(blank=True, default="", max_length=255)),
                ("shipping_company", models.CharField(blank=True, default="", max_length=255)),
                ("shipping_street", models.CharField(blank=True, default="", max_length=255)),
                ("shipping_street_2", models.CharField(blank=True, default="", max_length=255)),
                ("shipping_postal_code", models.CharField(blank=True, default="", max_length=32)),
                ("shipping_city", models.CharField(blank=True, default="", max_length=255)),
                ("shipping_state_or_province", models.CharField(blank=True, default="", max_length=255)),
                ("shipping_phone", models.CharField(blank=True, default="", max_length=128)),
                ("shipping_country", models.CharField(blank=True, default="", max_length=255)),
                ("shipping_country_iso", models.CharField(blank=True, default="", max_length=8)),
                ("shipping_tax_id_number", models.CharField(blank=True, default="", max_length=255)),
                ("contains_ebay_plus_transaction", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kid", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="client", to="database.kid")),
            ],
            options={
                "db_table": "database_client",
            },
        ),
    ]
