# Generated by Django 6.0.0 on 2026-07-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0041_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="date",
            new_name="order_date",
        ),
        migrations.RenameField(
            model_name="orders",
            old_name="payment_status",
            new_name="full_amount",
        ),
        migrations.AddField(
            model_name="orders",
            name="already_paid",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="delivery_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="invoice_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="invoice_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="paid_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="payment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="payment_function",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="payment_method",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="shipping_method",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="orders",
            name="shipping_tax_rate",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("afterbuy_item_id", models.CharField(max_length=255)),
                ("article_number", models.CharField(blank=True, default="", max_length=255)),
                ("alternative_item_number", models.CharField(blank=True, default="", max_length=255)),
                ("alternative_item_number_1", models.CharField(blank=True, default="", max_length=255)),
                ("platform_item_id", models.CharField(blank=True, default="", max_length=255)),
                ("platform_order_id", models.CharField(blank=True, default="", max_length=255)),
                ("title", models.TextField(blank=True, default="")),
                ("quantity", models.IntegerField(blank=True, null=True)),
                ("item_price", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("original_item_price", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                ("item_shipping_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("eco_fee", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("tax_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("tax_collected_by", models.CharField(blank=True, default="", max_length=255)),
                ("item_weight", models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ("item_end_date", models.DateTimeField(blank=True, null=True)),
                ("afterbuy_item_modified_at", models.DateTimeField(blank=True, null=True)),
                ("platform_name", models.CharField(blank=True, default="", max_length=255)),
                ("user_defined_flag", models.CharField(blank=True, default="", max_length=255)),
                ("internal_item_type", models.CharField(blank=True, default="", max_length=255)),
                ("item_details_done", models.BooleanField(default=False)),
                ("is_amazon_invoiced", models.BooleanField(default=False)),
                ("is_external_invoice", models.BooleanField(default=False)),
                ("ebay_transaction_id", models.CharField(blank=True, default="", max_length=255)),
                ("is_ebay_plus_transaction", models.BooleanField(default=False)),
                ("ebay_feedback_completed", models.BooleanField(default=False)),
                ("ebay_feedback_received", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="database.orders")),
            ],
            options={"db_table": "database_order_items"},
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(fields=("order", "afterbuy_item_id"), name="unique_afterbuy_item_per_order"),
        ),
    ]
