# Generated by Django 5.2.15 on 2026-07-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0044_orders_memo_sync_error_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ean',
            name='reserved_jv',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='ean',
            name='reserved_xl',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
