# Generated by Django 5.2.15 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0045_ean_reserved_jv_ean_reserved_xl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ean",
            name="ebay_jv",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="ean",
            name="ebay_xl",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="ean",
            name="hood_jv",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="ean",
            name="hood_xl",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="ean",
            name="kaufland_jv",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="ean",
            name="kaufland_xl",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="ean",
            name="main_ean",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="ean",
            name="otto_jv",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="ean",
            name="otto_xl",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="ean",
            name="reserved_jv",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="ean",
            name="reserved_xl",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="ean",
            name="xl",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
