# Generated by Django 5.2.15 on 2026-08-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0046_alter_ean_marketplace_fields_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
