const Map<String, String> appLabelsDe = <String, String>{
  'login': 'Anmeldung',
  'login_title': 'Anmeldung',
  'login_subtitle': 'Zugriff auf das System',
  'username': 'Login',
  'password': 'Passwort',
  'forgot_password': 'Passwort vergessen?',
  'reset_password_title': 'Passwort zurücksetzen',
  'reset_email_help': 'E-Mail eingeben, um einen Reset-Code zu erhalten.',
  'reset_code_help': 'Den 6-stelligen Code aus der E-Mail eingeben.',
  'reset_password_help': 'Neues Passwort für das Konto erstellen.',
  'send_reset_code': 'Reset-Code senden',
  'reset_code': 'Reset-Code',
  'update_password': 'Passwort aktualisieren',
  'reset_code_sent':
      'Wenn die E-Mail existiert, wurde ein Reset-Code gesendet.',
  'password_reset_success':
      'Passwort wurde zurückgesetzt. Anmeldung ist jetzt möglich.',
  'reset_email_invalid': 'Gültige E-Mail eingeben.',
  'reset_code_invalid': 'Der Code muss 6 Ziffern haben.',
  'reset_password_mismatch': 'Passwortbestätigung stimmt nicht überein.',
  'reset_password_length':
      'Passwort muss zwischen 8 und 128 Zeichen lang sein.',
  'reset_password_requirements':
      'Passwort muss Großbuchstaben, Kleinbuchstaben und eine Zahl enthalten.',
  'reset_request_failed': 'Reset-Code konnte nicht gesendet werden.',
  'reset_confirm_failed': 'Passwort konnte nicht zurückgesetzt werden.',
  'session_expired_login_again':
      'Sitzung abgelaufen. Bitte einmal mit Passwort anmelden.',
  'language': 'Sprache',
  'warehouse_map': 'Lagerkarte',
  'warehouse_map_subtitle': 'Lagerplan und Artikelstandorte',
  'warehouse_map_hint': 'Zum Zoomen aufziehen und die Karte verschieben.',
  'warehouse_map_semantics':
      'Lagerkarte mit Showroom in Zone A, Zonen bis M und Warenannahmebereich.',
  'warehouse_showroom': 'SHOWROOM',
  'warehouse_map_zoom_in': 'Vergrößern',
  'warehouse_map_zoom_out': 'Verkleinern',
  'cancel': 'Abbrechen',
  'next': 'Weiter',
  'prev': 'Zurück',
  'skip': '',
  'yes': 'Ja',
  'no': 'Nein',
  'save': 'Speichern',
  'add': 'Hinzufügen',
  'remove': 'Entfernen',
  'return_to_stock': 'Zurück auf Lager',
  'confirm_return_to_stock': '{location} als zurück auf Lager markieren?',
  'confirm_remove_location':
      'Das aelteste aktive Produkt vom Platz {location} entfernen?',
  'return_marked': '{count} Teil(e) als zurück auf Lager markiert.',
  'print': 'Drucken',
  'print_now': 'Jetzt drucken',
  'print_image': 'Bild drucken',
  'printer_setup': 'Drucker einrichten',
  'printer_actions': 'Druckeraktionen',
  'products_tab': 'Produkte',
  'product_details': 'Produktdetails',
  'product_information': 'Produktinformationen',
  'warehouse_locations': 'Lagerplätze',
  'scan': 'SCAN',
  'scan_action_title': 'Scan-Aktion',
  'scan_action_subtitle': 'Aktion für das gescannte Produkt auswählen.',
  'scan_source_title': 'Eingabequelle',
  'scan_source_subtitle': '{action}: Quelle wählen',
  'scan_by_qr': 'Per QR scannen',
  'scan_by_kid': 'KID-Nummer eingeben',
  'scan_by_section_slot': 'Nach Bereich + Fach',
  'scan_source_empty': 'Leerer Artikel',
  'category_optional': 'Kategorie (optional)',
  'subcategory_optional': 'Unterkategorie (optional)',
  'no_selection': 'Keine Auswahl',
  'kid_number': 'KID-Nummer',
  'kid_required': 'KID-Nummer ist erforderlich.',
  'enter_kid_for_add': 'KID-Nummer für ADD eingeben',
  'enter_kid_for_remove': 'KID-Nummer für REMOVE eingeben',
  'no_active_products_for_selection':
      'Keine aktiven Produkte für die Auswahl gefunden.',
  'no_active_products_for_location':
      'Keine aktiven Produkte für Platz {location} gefunden.',
  'select_printer': 'Drucker auswählen',
  'connect': 'Verbinden',
  'update_available_title': 'Update verfügbar',
  'update_later': 'Später',
  'update_now': 'Aktualisieren',
  'permission_dont_allow': 'Nicht erlauben',
  'permission_allow': 'Erlauben',
  'preview_only_mode': 'Nur Vorschau',
  'preview_only_help': 'Vorschau anzeigen und nicht drucken.',
  'label_type': 'Etikettentyp',
  'label_type_value': 'Etikettentyp {value}',
  'label_layout': 'Etikettenlayout',
  'label_layout_main': 'Haupttext',
  'label_layout_parts': 'Teile',
  'label_layout_size': 'Größe',
  'label_layout_move': 'Verschieben',
  'label_layout_decrease': 'Verkleinern',
  'label_layout_increase': 'Vergrößern',
  'label_layout_left': 'Links',
  'label_layout_up': 'Nach oben',
  'label_layout_down': 'Nach unten',
  'label_layout_right': 'Rechts',
  'label_layout_reset_defaults': 'Standardwerte zurücksetzen',
  'label_layout_saved': 'Etikettenlayout für alle Benutzer gespeichert.',
  'label_layout_sync_failed':
      'Lokal gespeichert, aber globales Layout konnte nicht synchronisiert werden.',
  'density': 'Dichte',
  'density_value': 'Dichte {value}',
  'order': 'Bestellung',
  'confirm_return': 'Rückgabe bestätigen',
  'warehouse_feed': 'Lagerübersicht',
  'realtime_intakes': 'Echtzeit-Vorgänge',
  'no_products':
      'Noch keine Produkte in der Liste.\nTippe auf SCAN, um Produkte hinzuzufügen oder zu entfernen.',
  'logout': 'Abmelden',
  'account': 'Konto',
  'profile': 'Profil',
  'login_value': 'Login',
  'email_value': 'E-Mail',
  'first_name': 'Vorname',
  'last_name': 'Nachname',
  'phone_number': 'Telefon',
  'profile_status': 'Status',
  'profile_role': 'Rolle',
  'profile_user': 'Benutzer',
  'profile_username': 'Benutzername',
  'profile_role_admin': 'Administrator',
  'profile_role_user': 'Benutzer',
  'profile_status_pending': 'Ausstehend',
  'profile_status_approved': 'Freigegeben',
  'profile_status_rejected': 'Abgelehnt',
  'profile_status_unknown': 'Unbekannt',
  'avatar_url': 'Avatar',
  'api_base_url': 'API-URL',
  'upload_avatar': 'Avatar hochladen',
  'save_profile': 'Profil speichern',
  'change_password': 'Passwort ändern',
  'current_password': 'Aktuelles Passwort',
  'new_password': 'Neues Passwort',
  'confirm_password': 'Passwort bestätigen',
  'profile_updated': 'Profil aktualisiert.',
  'profile_update_failed': 'Profil konnte nicht aktualisiert werden: {error}',
  'password_changed': 'Passwort geändert.',
  'password_change_failed': 'Passwort konnte nicht geändert werden: {error}',
  'profile_load_failed': 'Profil konnte nicht geladen werden: {error}',
  'api_base_saved': 'API-URL gespeichert.',
  'avatar_uploaded': 'Avatar hochgeladen.',
  'check_updates': 'Updates prüfen',
  'update_available': 'Update verfügbar',
  'update_app': 'App aktualisieren',
  'printer_connected': 'Drucker verbunden',
  'connect_printer': 'Drucker verbinden',
  'more': 'Mehr',
  'loading': 'Laden...',
  'opening_app': 'App wird geöffnet...',
  'sort': 'Sortierung',
  'newest_first': 'Neueste zuerst',
  'oldest_first': 'Älteste zuerst',
  'search': 'Suche',
  'activity': 'Aktivität',
  'filter_list': 'Liste filtern',
  'load_filters_failed': 'Filteroptionen konnten nicht geladen werden: {error}',
  'filter_place': 'Platz',
  'all_places': 'Alle Plätze',
  'inventory_search_loading_hint': 'Produkte suchen',
  'inventory_search_hint': 'Unter {count} Produkten suchen',
  'filter_section': 'Bereich',
  'filter_destination': 'Ziel',
  'filter_status': 'Status',
  'all_destinations': 'Alle',
  'warehouse': 'Lager',
  'store': 'Shop',
  'b_ware_only': 'Nur B-Ware',
  'in_transit_only': 'Nur unterwegs',
  'all_sections': 'Alle Bereiche',
  'filter_quantity': 'Menge',
  'all_quantities': 'Alle Mengen',
  'filter_room': 'Raum',
  'all_rooms': 'Alle Räume',
  'filter_type': 'Typ',
  'all_types': 'Alle Typen',
  'filter_company': 'Firma',
  'all_companies': 'Alle Firmen',
  'filter_color': 'Farbe',
  'all_colors': 'Alle Farben',
  'filter_material': 'Material',
  'all_materials': 'Alle Materialien',
  'all_activity': 'Alle Aktivitäten',
  'load_more': 'Mehr laden',
  'active_filters_count': 'Filter: {count}',
  'apply': 'Anwenden',
  'reset': 'Zurücksetzen',
  'kid': 'KID',
  'section_slot': 'Bereich/Fach',
  'product_key': 'Firma',
  'pallet_placeholder': 'Paletten',
  'count': 'Menge',
  'boxes': 'Boxen',
  'unit': 'Einheit',
  'memo': 'Notiz',
  'active': 'Aktiv',
  'inactive': 'Inaktiv',
  'auto_delete_in': 'Auto-Löschung in {days} Tg.',
  'auto_delete_due': 'Auto-Löschung fällig',
  'removed': 'Entfernt',
  'scan_qr': 'QR scannen',
  'align_qr': 'QR-Code in den Rahmen halten',
  'update_available_body':
      'Eine neue Version ist verfügbar.\nAktuell: {current}\nNeu: {latest}\nKanal: {channel}',
  'settings': 'Einstellungen',
  'camera_permission_title': 'Kamera-Berechtigung',
  'camera_permission_body':
      'Die Kamera wird zum Scannen benötigt.\nBitte Zugriff erlauben.',
  'bluetooth_permission_title': 'Bluetooth-Berechtigung',
  'bluetooth_permission_body':
      'Bluetooth wird für den Drucker benötigt.\nBitte Zugriff erlauben.',
  'bluetooth_permission_settings':
      'Bluetooth-Berechtigung wurde nicht erteilt. Bitte in den Einstellungen erlauben.',
  'bluetooth_disabled': 'Bluetooth ist deaktiviert.',
  'no_printers_found':
      'Keine Bluetooth-Drucker gefunden. Drucker einschalten und erneut versuchen.',
  'printer_selection_cancelled': 'Druckerauswahl abgebrochen.',
  'printer_connect_failed':
      'Drucker konnte nicht verbunden werden: {name} ({address}).',
  'load_list_failed_http': 'Liste laden fehlgeschlagen: HTTP {code}',
  'load_list_invalid': 'Liste laden fehlgeschlagen: ungültige Antwort.',
  'load_list_error': 'Liste laden Fehler: {error}',
  'network_unavailable':
      'Keine Internetverbindung. Der Server ist derzeit nicht erreichbar.',
  'network_unavailable_load':
      'Keine Internetverbindung. Die Liste kann derzeit nicht geladen werden.',
  'network_unavailable_login':
      'Keine Internetverbindung. Anmeldung ist derzeit nicht möglich.',
  'action_failed_error': 'Aktion fehlgeschlagen: {error}',
  'login_failed_error': 'Anmeldung fehlgeschlagen: {error}',
  'latest_version': 'Sie haben die neueste Version ({version}).',
  'failed_check_updates': 'Updates konnten nicht geprüft werden.',
  'update_link_missing': 'Update-Link ist nicht konfiguriert.',
  'failed_open_update': 'Update-Link konnte nicht geöffnet werden.',
  'update_started': 'Update-Download gestartet.',
  'camera_permission_denied': 'Kamera-Berechtigung nicht erteilt.',
  'bluetooth_permission_denied': 'Bluetooth-Berechtigung nicht erteilt.',
  'printer_connected_message': 'Drucker verbunden.',
  'preview_only_on': 'Vorschau ist an: nichts gedruckt.',
  'print_canceled': 'Druck abgebrochen.',
  'printed_labels': '{count} Etiketten gedruckt (Nimbot B1).',
  'kid_not_found': 'KID im QR-Code nicht gefunden.',
  'photos_upload_failed': 'Fotos konnten nicht hochgeladen werden: {count}.',
  'photos_upload_recovered':
      'Erfolgreich nach erneutem Versuch hochgeladen: {count}.',
  'photo_upload_retry_title': 'Fehlgeschlagene Uploads wiederholen',
  'photo_upload_retry_body':
      '{count} Foto(s) konnten nicht hochgeladen werden. Jetzt erneut versuchen?',
  'retry': 'Erneut',
  'order_id_missing': 'OrderID im QR-Code nicht gefunden.',
  'afterbuy_unavailable': 'Afterbuy nicht verfügbar: {error}',
  'image_printed': 'Bild gedruckt (Nimbot B1).',
  'invalid_width_height': 'Ungültige Breite/Höhe.',
  'print_preview': 'Druckvorschau',
  'label_preview': 'Etikettenvorschau',
  'labels_preview': 'Etikettenvorschau ({count})',
  'close': 'Schließen',
  'step_title': 'Schritt {step}/{total}',
  'number_of_boxes': 'Anzahl der Boxen',
  'location': 'Ort',
  'store_destination_store': 'Geschäft',
  'store_destination_warehouse': 'Lager',
  'warehouse_place': 'Lagerplatz',
  'enter_place': 'Platz eingeben',
  'format_place': 'Format wie 88 oder 88A verwenden',
  'warehouse_place_taken':
      'Dieser Lagerplatz ist bereits belegt. Bitte einen neuen eingeben.',
  'take_photos_question': 'Produktfotos machen? Bis zu 10 Fotos.',
  'take_photos': 'Fotos machen',
  'skip_photos': 'Fotos überspringen',
  'photo_title': 'Foto {current}/{total}',
  'add_one_more_photo': 'Noch ein Foto hinzufügen?',
  'add_photo': 'Foto hinzufügen',
  'add_photos': 'Fotos hinzufügen',
  'photos_added': '{count} Foto(s) hinzugefügt.',
  'photos_limit_reached':
      'Dieses Produkt hat bereits die maximale Anzahl von 10 Fotos.',
  'continue': 'Weiter',
  'ordered_items': 'Bestellte Artikel (Afterbuy):',
  'no_structured_items': 'Keine strukturierten Artikel aus Afterbuy erkannt.',
  'mark_as_returned': 'Als zurückgegeben markieren:',
  'na': 'k. A.',
  'scan_action_help': 'Aktion für das gescannte Produkt auswählen.',
  'print_image_title': 'Bild drucken',
  'print_image_source_title': 'Bildquelle',
  'gallery': 'Galerie',
  'manual': 'Manual',
  'printer_setup_saved':
      'Drucker gespeichert: {width}x{height}, Typ {type}, Dichte {density}, Vorschau {preview}.',
  'printer_hint': 'Für dieses B1/T50-Setup: 384x640, Etikettentyp 1, Dichte 5.',
  'parts_quantity_title': 'Teileanzahl',
  'parts_quantity_help': 'Anzahl der Teile dieses Produkts eingeben.',
  'parts_label': 'Teile',
  'quantity_min_error': 'Die Anzahl muss größer als 0 sein.',
  'enter_number_min': 'Zahl eingeben >= {min}',
  'enter_number_range': 'Zahl von {min} bis {max} eingeben.',
  'item_added': 'Artikel hinzugefügt: {location}, Boxen: {boxes}.',
  'error_kid_missing': 'KID fehlt im QR-Payload.',
  'error_qr_required': 'QR-Code ist erforderlich.',
  'create_intake_failed_unauthorized':
      'Anlage fehlgeschlagen: HTTP 401 unauthorized',
  'create_intake_failed_http': 'Anlage fehlgeschlagen: HTTP {code}',
  'create_intake_failed_http_with_details':
      'Anlage fehlgeschlagen: HTTP {code}. {details}',
  'create_intake_failed_duplicate':
      'Produkt existiert bereits in der Eingangsliste fuer dieselbe Einheit/Box.',
  'create_intake_response_invalid': 'Antwort beim Anlegen ist kein Objekt.',
  'delete_intake_failed_unauthorized':
      'Löschen fehlgeschlagen: HTTP 401 unauthorized',
  'delete_intake_failed_http': 'Löschen fehlgeschlagen: HTTP {code}',
  'no_active_products':
      'Keine aktiven Produkte in der lokalen Liste für OrderID {order}.',
  'returned_marked': 'Rückgabe: {count} Teil(e) entfernt markiert.',
  'label_width': 'Etikettenbreite (px)',
  'label_height': 'Etikettenhöhe (px)',
  'on': 'an',
  'off': 'aus',
  'unknown_device': 'Unbekanntes Gerät',
  'paired': 'Gekoppelt',
  'not_paired': 'Nicht gekoppelt',
  'price': 'Preis',
  'date': 'Datum',
  'ean': 'EAN',
  'sku': 'SKU',
  'size': 'Größe',
  'color': 'Farbe',
  'color_schwarz': 'Schwarz',
  'color_weiss': 'Weiß',
  'color_grau': 'Grau',
  'color_silber': 'Silber',
  'color_beige': 'Beige',
  'color_braun': 'Braun',
  'color_blau': 'Blau',
  'color_hellblau': 'Hellblau',
  'color_marineblau': 'Marineblau',
  'color_turkis': 'Türkis',
  'color_grun': 'Grün',
  'color_hellgrun': 'Hellgrün',
  'color_gelb': 'Gelb',
  'color_orange': 'Orange',
  'color_rot': 'Rot',
  'color_bordeaux': 'Bordeaux',
  'color_rosa': 'Rosa',
  'color_lila': 'Lila',
  'color_violett': 'Violett',
  'color_mehrfarbig': 'Mehrfarbig',
  'b_ware': 'B-Ware',
  'b_ware_question': 'Ist das ein B-Ware-Produkt?',
  'b_ware_comment': 'Kommentar (optional)',
  'in_transit': 'Unterwegs',
  'in_transit_question': 'Ist dieses Produkt unterwegs?',
  'occupied_slot_options_body':
      'Lagerplatz: {slot}\n\nAnderen Platz verwenden oder Menge zu diesem Platz hinzufuegen.',
  'existing_product_found_title': 'Gleiches Produkt gefunden',
  'existing_product_found_body':
      'Das gleiche Produkt existiert bereits in: {locations}.\nNeuer Platz: {target}.\n\nWaehlen: Menge zum bestehenden Produkt hinzufuegen oder als neues Produkt anlegen.',
  'existing_product_slot_taken_title': 'Lagerplatz ist bereits belegt',
  'existing_product_slot_taken_body':
      'Der Lagerplatz {slot} ist bereits belegt.\n\nWaehlen: mit neuer Platznummer anlegen oder Menge zum bestehenden Produkt hinzufuegen.',
  'existing_product_create_new': 'Neu anlegen',
  'existing_product_add_quantity': 'Menge hinzufuegen',
  'oldest_item_date': 'Aeltestes Produktdatum: {date}',
  'remove_fifo_hint': 'Es wird das aelteste Produkt entfernt (FIFO).',
};
