const Map<String, String> appLabelsEn = <String, String>{
  'login': 'Login',
  'login_title': 'Login',
  'login_subtitle': 'Secure access',
  'username': 'Login',
  'password': 'Password',
  'forgot_password': 'Forgot password?',
  'reset_password_title': 'Reset password',
  'reset_email_help': 'Enter your email to receive a reset code.',
  'reset_code_help': 'Enter the 6-digit code from your email.',
  'reset_password_help': 'Create a new password for your account.',
  'send_reset_code': 'Send reset code',
  'reset_code': 'Reset code',
  'update_password': 'Update password',
  'reset_code_sent': 'If the email exists, a reset code was sent.',
  'password_reset_success': 'Password was reset. You can sign in now.',
  'reset_email_invalid': 'Enter a valid email address.',
  'reset_code_invalid': 'Code must be 6 digits.',
  'reset_password_mismatch': 'Password confirmation does not match.',
  'reset_password_length': 'Password must be between 8 and 128 characters.',
  'reset_password_requirements':
      'Password must include uppercase, lowercase and a number.',
  'reset_request_failed': 'Failed to send reset code.',
  'reset_confirm_failed': 'Failed to reset password.',
  'fingerprint_login': 'Login with fingerprint',
  'fingerprint_next': 'Use fingerprint next time',
  'fingerprint_unavailable': 'Fingerprint is not available on this device.',
  'fingerprint_reason': 'Authenticate to log in to Warehub.',
  'fingerprint_setup_canceled': 'Fingerprint setup was canceled.',
  'session_expired_login_again': 'Session expired. Login with password once.',
  'enable_fingerprint_title': 'Enable fingerprint login?',
  'enable_fingerprint_body': 'Use fingerprint for faster login next time?',
  'enable': 'Enable',
  'later': 'Later',
  'language': 'Language',
  'cancel': 'Cancel',
  'next': 'Next',
  'prev': 'Prev',
  'skip': 'Skip',
  'yes': 'Yes',
  'no': 'No',
  'save': 'Save',
  'add': 'Add',
  'remove': 'Remove',
  'print': 'Print',
  'print_now': 'Print now',
  'print_image': 'Print image',
  'printer_setup': 'Printer setup',
  'printer_actions': 'Printer actions',
  'products_tab': 'Products',
  'scan': 'SCAN',
  'scan_action_title': 'Scan action',
  'scan_action_subtitle': 'Choose what to do with the scanned product.',
  'scan_source_title': 'Input source',
  'scan_source_subtitle': '{action}: choose source',
  'scan_by_qr': 'Scan by QR',
  'scan_by_kid': 'Enter KID number',
  'scan_by_section_slot': 'By section + slot',
  'scan_source_empty': 'Empty product',
  'category_optional': 'Category (optional)',
  'subcategory_optional': 'Subcategory (optional)',
  'no_selection': 'No selection',
  'kid_number': 'KID number',
  'kid_required': 'KID number is required.',
  'enter_kid_for_add': 'Enter KID number for ADD',
  'enter_kid_for_remove': 'Enter KID number for REMOVE',
  'no_active_products_for_selection':
      'No active products found for selected input.',
  'no_active_products_for_location':
      'No active products found for location {location}.',
  'select_printer': 'Select printer',
  'connect': 'Connect',
  'update_available_title': 'Update available',
  'update_later': 'Later',
  'update_now': 'Update',
  'permission_dont_allow': 'Don\'t allow',
  'permission_allow': 'Allow',
  'preview_only_mode': 'Preview only mode',
  'preview_only_help': 'Show label preview and do not print.',
  'label_type': 'Label type',
  'label_type_value': 'Label type {value}',
  'label_layout': 'Label layout',
  'label_layout_main': 'Main',
  'label_layout_parts': 'Parts',
  'label_layout_size': 'Size',
  'label_layout_move': 'Move',
  'label_layout_decrease': 'Decrease',
  'label_layout_increase': 'Increase',
  'label_layout_left': 'Left',
  'label_layout_up': 'Up',
  'label_layout_down': 'Down',
  'label_layout_right': 'Right',
  'label_layout_reset_defaults': 'Reset defaults',
  'label_layout_saved': 'Label layout saved for all users.',
  'label_layout_sync_failed':
      'Saved locally, but failed to sync global layout.',
  'density': 'Density',
  'density_value': 'Density {value}',
  'order': 'Order',
  'confirm_return': 'Confirm return',
  'warehouse_feed': 'Warehouse Feed',
  'realtime_intakes': 'Realtime intake operations',
  'units_count': 'Units  {count}',
  'no_products': 'No products in list yet.\nTap SCAN to add or remove product.',
  'logout': 'Logout',
  'account': 'Account',
  'profile': 'Profile',
  'login_value': 'Login',
  'email_value': 'Email',
  'first_name': 'First name',
  'last_name': 'Last name',
  'phone_number': 'Phone',
  'confirm_password': 'Confirm password',
  'avatar_url': 'Avatar URL',
  'api_base_url': 'API URL',
  'upload_avatar': 'Upload avatar',
  'save_profile': 'Save profile',
  'change_password': 'Change password',
  'current_password': 'Current password',
  'new_password': 'New password',
  'profile_updated': 'Profile updated.',
  'profile_update_failed': 'Profile update failed: {error}',
  'password_changed': 'Password changed.',
  'password_change_failed': 'Password change failed: {error}',
  'profile_load_failed': 'Failed to load profile: {error}',
  'api_base_saved': 'API URL saved.',
  'avatar_uploaded': 'Avatar uploaded.',
  'check_updates': 'Check updates',
  'update_available': 'Update available',
  'update_app': 'Update app',
  'printer_connected': 'Printer connected',
  'connect_printer': 'Connect printer',
  'more': 'More',
  'loading': 'Loading...',
  'opening_app': 'Opening app...',
  'sort': 'Sort',
  'newest_first': 'Newest first',
  'oldest_first': 'Oldest first',
  'search': 'Search',
  'activity': 'Activity',
  'filter_list': 'Filter list',
  'inventory_search_hint': 'Search KID, order, product or EAN',
  'filter_section': 'Section',
  'filter_destination': 'Destination',
  'filter_status': 'Status',
  'all_destinations': 'All',
  'warehouse': 'Warehouse',
  'store': 'Store',
  'b_ware_only': 'B-Ware only',
  'in_transit_only': 'In transit only',
  'all_sections': 'All sections',
  'all_activity': 'All activity',
  'load_more': 'Load more',
  'active_filters_count': 'Filters: {count}',
  'apply': 'Apply',
  'reset': 'Reset',
  'kid': 'KID',
  'section_slot': 'Section/Slot',
  'product_key': 'Company',
  'pallet_placeholder': 'Pallets',
  'count': 'Count',
  'boxes': 'Boxes',
  'unit': 'Unit',
  'memo': 'Memo',
  'active': 'Active',
  'inactive': 'Inactive',
  'auto_delete_in': 'Auto-delete in {days}d',
  'auto_delete_due': 'Auto-delete due',
  'removed': 'Removed',
  'scan_qr': 'Scan QR',
  'align_qr': 'Align QR code in frame',
  'update_available_body':
      'A new app version is available.\nCurrent: {current}\nLatest: {latest}\nChannel: {channel}',
  'settings': 'Settings',
  'camera_permission_title': 'Camera permission',
  'camera_permission_body':
      'Camera is required to scan QR codes.\nPlease allow camera access.',
  'bluetooth_permission_title': 'Bluetooth permission',
  'bluetooth_permission_body':
      'Bluetooth/Nearby is required to connect the printer.\nPlease allow access.',
  'bluetooth_permission_settings':
      'Bluetooth permission was not granted. Allow Nearby devices/Bluetooth in app settings.',
  'bluetooth_disabled': 'Bluetooth is disabled.',
  'no_printers_found':
      'No bluetooth printers found. Turn on printer and try again.',
  'printer_selection_cancelled': 'Printer selection was cancelled.',
  'printer_connect_failed':
      'Failed to pair/connect printer {name} ({address}).',
  'load_list_failed_http': 'Load list failed: HTTP {code}',
  'load_list_invalid': 'Load list failed: invalid response.',
  'load_list_error': 'Load list error: {error}',
  'network_unavailable':
      'No internet connection. The server is unavailable right now.',
  'network_unavailable_load':
      'No internet connection. The list cannot be loaded right now.',
  'network_unavailable_login':
      'No internet connection. Login is unavailable right now.',
  'action_failed_error': 'Action failed: {error}',
  'login_failed_error': 'Login failed: {error}',
  'latest_version': 'You already have the latest version ({version}).',
  'failed_check_updates': 'Failed to check updates.',
  'update_link_missing': 'Update link is not configured.',
  'failed_open_update': 'Failed to open update link.',
  'update_started': 'Update download started.',
  'camera_permission_denied': 'Camera permission was not granted.',
  'bluetooth_permission_denied': 'Bluetooth permission was not granted.',
  'printer_connected_message': 'Printer connected.',
  'preview_only_on': 'Preview mode is ON: nothing printed.',
  'print_canceled': 'Print canceled.',
  'printed_labels': 'Printed {count} label(s) (Nimbot B1).',
  'kid_not_found': 'KID not found in QR code.',
  'photos_upload_failed': 'Photos failed to upload: {count}.',
  'photos_upload_recovered': 'Recovered photo uploads after retry: {count}.',
  'photo_upload_retry_title': 'Retry failed uploads',
  'photo_upload_retry_body':
      '{count} photo(s) still failed to upload. Retry now?',
  'retry': 'Retry',
  'order_id_missing': 'OrderID was not found in QR payload.',
  'afterbuy_unavailable': 'Afterbuy list unavailable: {error}',
  'image_printed': 'Image printed (Nimbot B1).',
  'invalid_width_height': 'Invalid width/height.',
  'print_preview': 'Print preview',
  'label_preview': 'Label preview',
  'labels_preview': 'Labels preview ({count})',
  'close': 'Close',
  'step_title': 'Step {step}/{total}',
  'number_of_boxes': 'Number of boxes',
  'location': 'Location',
  'store_destination_store': 'Store',
  'store_destination_warehouse': 'Warehouse',
  'warehouse_place': 'Warehouse place',
  'enter_place': 'Enter place',
  'format_place': 'Use format like 88 or 88A',
  'warehouse_place_taken':
      'This warehouse place is already in use. Enter a new one.',
  'occupied_slot_options_body':
      'Warehouse place: {slot}\n\nUse another place, or add quantity to this place.',
  'existing_product_found_title': 'Existing product found',
  'existing_product_found_body':
      'Same product already exists in: {locations}.\nNew location: {target}.\n\nChoose: add to existing quantity, or create as a new product.',
  'existing_product_slot_taken_title': 'Warehouse slot is already occupied',
  'existing_product_slot_taken_body':
      'Warehouse slot {slot} is already occupied.\n\nChoose: create with a new slot number, or add quantity to the existing product.',
  'existing_product_create_new': 'Create new',
  'existing_product_add_quantity': 'Add quantity',
  'take_photos_question': 'Take product photos? Up to 10 photos.',
  'take_photos': 'Take photos',
  'skip_photos': 'Skip photos',
  'photo_title': 'Photo {current}/{total}',
  'add_one_more_photo': 'Add one more photo?',
  'add_photo': 'Add photo',
  'continue': 'Continue',
  'ordered_items': 'Ordered items (Afterbuy):',
  'no_structured_items': 'No structured items parsed from Afterbuy page.',
  'mark_as_returned': 'Mark as returned:',
  'na': 'n/a',
  'scan_action_help': 'Choose what to do with the scanned product.',
  'print_image_title': 'Print image',
  'print_image_source_title': 'Image source',
  'gallery': 'Gallery',
  'manual': 'Manual',
  'printer_setup_saved':
      'Printer setup saved: {width}x{height}, type {type}, density {density}, preview-only {preview}.',
  'printer_hint': 'For this B1/T50 setup use 384x640, label type 1, density 5.',
  'parts_quantity_title': 'Parts quantity',
  'parts_quantity_help': 'Enter how many parts this product has.',
  'parts_label': 'Parts',
  'quantity_min_error': 'Quantity must be greater than 0.',
  'enter_number_min': 'Enter a number >= {min}',
  'enter_number_range': 'Enter a number from {min} to {max}.',
  'item_added': 'Item added: {location}, boxes: {boxes}.',
  'error_kid_missing': 'KID is missing in QR payload.',
  'error_qr_required': 'QR code is required.',
  'create_intake_failed_unauthorized':
      'Create intake failed: HTTP 401 unauthorized',
  'create_intake_failed_http': 'Create intake failed: HTTP {code}',
  'create_intake_failed_http_with_details':
      'Create intake failed: HTTP {code}. {details}',
  'create_intake_failed_duplicate':
      'This product is already in the intake list for the same unit/box.',
  'create_intake_response_invalid': 'Create intake response is not an object.',
  'delete_intake_failed_unauthorized':
      'Delete intake failed: HTTP 401 unauthorized',
  'delete_intake_failed_http': 'Delete intake failed: HTTP {code}',
  'no_active_products':
      'No active products found in local list for OrderID {order}.',
  'returned_marked': 'Returned: {count} part(s) marked as removed.',
  'oldest_item_date': 'Oldest item date: {date}',
  'remove_fifo_hint': 'Will remove the oldest item (FIFO).',
  'label_width': 'Label width (px)',
  'label_height': 'Label height (px)',
  'on': 'on',
  'off': 'off',
  'unknown_device': 'Unknown device',
  'paired': 'Paired',
  'not_paired': 'Not paired',
  'price': 'Price',
  'date': 'Date',
  'ean': 'EAN',
  'sku': 'SKU',
  'size': 'Size',
  'color': 'Color',
  'color_schwarz': 'Black',
  'color_weiss': 'White',
  'color_grau': 'Gray',
  'color_silber': 'Silver',
  'color_beige': 'Beige',
  'color_braun': 'Brown',
  'color_blau': 'Blue',
  'color_hellblau': 'Light blue',
  'color_marineblau': 'Navy',
  'color_turkis': 'Turquoise',
  'color_grun': 'Green',
  'color_hellgrun': 'Light green',
  'color_gelb': 'Yellow',
  'color_orange': 'Orange',
  'color_rot': 'Red',
  'color_bordeaux': 'Burgundy',
  'color_rosa': 'Pink',
  'color_lila': 'Lilac',
  'color_violett': 'Violet',
  'color_mehrfarbig': 'Multicolor',
  'b_ware': 'B-Ware',
  'b_ware_question': 'Is this a B-Ware product?',
  'b_ware_comment': 'Comment (optional)',
  'in_transit': 'In Transit',
  'in_transit_question': 'Is this product in transit?',
};
