const Map<String, String> appLabelsRu = <String, String>{
  'login': 'Вход',
  'login_title': 'Вход',
  'login_subtitle': 'Безопасный доступ',
  'username': 'Логин',
  'password': 'Пароль',
  'fingerprint_login': 'Вход по отпечатку',
  'fingerprint_next': 'Использовать отпечаток в следующий раз',
  'fingerprint_unavailable': 'Отпечаток недоступен на этом устройстве.',
  'fingerprint_reason': 'Подтвердите вход в Warehub.',
  'fingerprint_setup_canceled': 'Настройка отпечатка отменена.',
  'session_expired_login_again': 'Сессия истекла. Войдите один раз по паролю.',
  'enable_fingerprint_title': 'Включить вход по отпечатку?',
  'enable_fingerprint_body': 'Использовать отпечаток для быстрого входа?',
  'enable': 'Включить',
  'later': 'Позже',
  'language': 'Язык',
  'cancel': 'Отмена',
  'next': 'Далее',
  'prev': 'Назад',
  'skip': 'Пропустить',
  'save': 'Сохранить',
  'add': 'Добавить',
  'remove': 'Удалить',
  'print': 'Печать',
  'print_now': 'Печатать',
  'print_image': 'Печать изображения',
  'printer_setup': 'Настройка принтера',
  'scan': 'SCAN',
  'scan_action_title': 'Действие сканирования',
  'scan_action_subtitle': 'Выберите действие для отсканированного товара.',
  'scan_source_title': 'Источник ввода',
  'scan_source_subtitle': '{action}: выберите источник',
  'scan_by_qr': 'Сканировать QR',
  'scan_by_kid': 'Ввести KID номер',
  'scan_by_section_slot': 'По секции и месту',
  'scan_source_empty': 'Пустой товар',
  'category_optional': 'Категория (необязательно)',
  'subcategory_optional': 'Подкатегория (необязательно)',
  'no_selection': 'Без выбора',
  'kid_number': 'KID номер',
  'kid_required': 'KID номер обязателен.',
  'enter_kid_for_add': 'Введите KID номер для ADD',
  'enter_kid_for_remove': 'Введите KID номер для REMOVE',
  'no_active_products_for_selection':
      'Нет активных товаров для выбранного ввода.',
  'no_active_products_for_location':
      'Нет активных товаров для места {location}.',
  'select_printer': 'Выберите принтер',
  'connect': 'Подключить',
  'update_available_title': 'Доступно обновление',
  'update_later': 'Позже',
  'update_now': 'Обновить',
  'permission_dont_allow': 'Не разрешать',
  'permission_allow': 'Разрешить',
  'preview_only_mode': 'Только предпросмотр',
  'preview_only_help': 'Показывать предпросмотр и не печатать.',
  'label_type': 'Тип этикетки',
  'label_type_value': 'Тип этикетки {value}',
  'density': 'Плотность',
  'density_value': 'Плотность {value}',
  'order': 'Заказ',
  'confirm_return': 'Подтвердить возврат',
  'warehouse_feed': 'Лента склада',
  'realtime_intakes': 'Операции приемки в реальном времени',
  'units_count': 'Единиц  {count}',
  'no_products':
      'Пока нет товаров в списке.\nНажмите SCAN, чтобы добавить или удалить товар.',
  'logout': 'Выйти',
  'check_updates': 'Проверить обновления',
  'update_available': 'Обновление доступно',
  'update_app': 'Обновить приложение',
  'printer_connected': 'Принтер подключен',
  'connect_printer': 'Подключить принтер',
  'more': 'Ещё',
  'loading': 'Загрузка...',
  'opening_app': 'Открываем приложение...',
  'sort': 'Сортировка',
  'newest_first': 'Сначала новые',
  'oldest_first': 'Сначала старые',
  'search': 'Поиск',
  'activity': 'Активность',
  'filter_list': 'Фильтр списка',
  'all_sections': 'Все секции',
  'all_activity': 'Вся активность',
  'load_more': 'Загрузить ещё',
  'active_filters_count': 'Фильтры: {count}',
  'apply': 'Применить',
  'reset': 'Сбросить',
  'kid': 'KID',
  'section_slot': 'Секция/Слот',
  'product_key': 'Ключ товара',
  'count': 'Количество',
  'boxes': 'Коробки',
  'unit': 'Единица',
  'memo': 'Примечание',
  'active': 'Активный',
  'inactive': 'Неактивный',
  'auto_delete_in': 'Авто-удаление через {days} дн.',
  'auto_delete_due': 'Авто-удаление просрочено',
  'removed': 'Удалён',
  'scan_qr': 'Сканировать QR',
  'align_qr': 'Наведите QR-код в рамку',
  'update_available_body':
      'Доступна новая версия приложения.\nТекущая: {current}\nНовая: {latest}\nКанал: {channel}',
  'settings': 'Настройки',
  'camera_permission_title': 'Разрешение на камеру',
  'camera_permission_body':
      'Камера нужна для сканирования QR-кодов.\nПожалуйста, разрешите доступ.',
  'bluetooth_permission_title': 'Разрешение Bluetooth',
  'bluetooth_permission_body':
      'Bluetooth/Nearby нужен для подключения принтера.\nПожалуйста, разрешите доступ.',
  'bluetooth_permission_settings':
      'Разрешение Bluetooth не выдано. Разрешите доступ в настройках.',
  'bluetooth_disabled': 'Bluetooth отключён.',
  'no_printers_found':
      'Bluetooth-принтеры не найдены. Включите принтер и повторите попытку.',
  'printer_selection_cancelled': 'Выбор принтера отменён.',
  'printer_connect_failed':
      'Не удалось подключить принтер: {name} ({address}).',
  'load_list_failed_http': 'Ошибка загрузки списка: HTTP {code}',
  'load_list_invalid': 'Ошибка загрузки списка: некорректный ответ.',
  'load_list_error': 'Ошибка загрузки списка: {error}',
  'network_unavailable':
      'Нет подключения к интернету. Сервер сейчас недоступен.',
  'network_unavailable_load':
      'Нет подключения к интернету. Сейчас невозможно загрузить список.',
  'network_unavailable_login':
      'Нет подключения к интернету. Сейчас невозможно выполнить вход.',
  'action_failed_error': 'Действие не выполнено: {error}',
  'login_failed_error': 'Ошибка входа: {error}',
  'latest_version': 'У вас уже последняя версия ({version}).',
  'failed_check_updates': 'Не удалось проверить обновления.',
  'update_link_missing': 'Ссылка на обновление не настроена.',
  'failed_open_update': 'Не удалось открыть ссылку обновления.',
  'update_started': 'Загрузка обновления началась.',
  'camera_permission_denied': 'Разрешение на камеру не выдано.',
  'bluetooth_permission_denied': 'Разрешение Bluetooth не выдано.',
  'printer_connected_message': 'Принтер подключён.',
  'preview_only_on': 'Включён предпросмотр: печать не выполнена.',
  'print_canceled': 'Печать отменена.',
  'printed_labels': 'Напечатано {count} этикеток (Nimbot B1).',
  'kid_not_found': 'KID не найден в QR-коде.',
  'photos_upload_failed': 'Не удалось загрузить фото: {count}.',
  'photos_upload_recovered':
      'Успешно загружено после повторной попытки: {count}.',
  'photo_upload_retry_title': 'Повторить загрузку фото',
  'photo_upload_retry_body':
      'Не удалось загрузить фото: {count}. Повторить сейчас?',
  'retry': 'Повторить',
  'order_id_missing': 'OrderID не найден в QR-коде.',
  'afterbuy_unavailable': 'Afterbuy недоступен: {error}',
  'image_printed': 'Изображение напечатано (Nimbot B1).',
  'invalid_width_height': 'Неверная ширина/высота.',
  'print_preview': 'Предпросмотр печати',
  'label_preview': 'Предпросмотр этикетки',
  'labels_preview': 'Предпросмотр этикеток ({count})',
  'close': 'Закрыть',
  'step_title': 'Шаг {step}/{total}',
  'number_of_boxes': 'Количество коробок',
  'warehouse_place': 'Место на складе',
  'enter_place': 'Введите место',
  'format_place': 'Используйте формат 88 или 88A',
  'warehouse_place_taken': 'Это место на складе уже занято. Введите новое.',
  'take_photos_question': 'Сделать фото товара? До 10 фото.',
  'take_photos': 'Сделать фото',
  'skip_photos': 'Пропустить фото',
  'photo_title': 'Фото {current}/{total}',
  'add_one_more_photo': 'Добавить ещё одно фото?',
  'add_photo': 'Добавить фото',
  'continue': 'Продолжить',
  'ordered_items': 'Заказанные товары (Afterbuy):',
  'no_structured_items': 'Структурированные товары из Afterbuy не найдены.',
  'mark_as_returned': 'Отметить как возвращённые:',
  'na': 'н/д',
  'scan_action_help': 'Выберите действие для отсканированного товара.',
  'print_image_title': 'Печать изображения',
  'print_image_source_title': 'Источник изображения',
  'gallery': 'Галерея',
  'manual': 'Manual',
  'printer_setup_saved':
      'Принтер сохранён: {width}x{height}, тип {type}, плотность {density}, предпросмотр {preview}.',
  'printer_hint':
      'Для вашего B1/T50 используйте 384x640, тип этикетки 1, плотность 5.',
  'parts_quantity_title': 'Количество частей',
  'parts_quantity_help': 'Введите количество частей этого товара.',
  'parts_label': 'Части',
  'quantity_min_error': 'Количество должно быть больше 0.',
  'enter_number_min': 'Введите число >= {min}',
  'enter_number_range': 'Введите число от {min} до {max}.',
  'item_added': 'Товар добавлен: {location}, коробок: {boxes}.',
  'error_kid_missing': 'KID отсутствует в QR-данных.',
  'error_qr_required': 'QR-код обязателен.',
  'create_intake_failed_unauthorized': 'Ошибка создания: HTTP 401 unauthorized',
  'create_intake_failed_http': 'Ошибка создания: HTTP {code}',
  'create_intake_failed_http_with_details':
      'Ошибка создания: HTTP {code}. {details}',
  'create_intake_failed_duplicate':
      'Товар уже есть в списке приемки для той же единицы/коробки.',
  'create_intake_response_invalid': 'Ответ create intake не объект.',
  'delete_intake_failed_unauthorized': 'Ошибка удаления: HTTP 401 unauthorized',
  'delete_intake_failed_http': 'Ошибка удаления: HTTP {code}',
  'no_active_products':
      'Нет активных товаров в локальном списке для OrderID {order}.',
  'returned_marked': 'Возврат: отмечено удалёнными частей: {count}.',
  'label_width': 'Ширина этикетки (px)',
  'label_height': 'Высота этикетки (px)',
  'on': 'вкл',
  'off': 'выкл',
  'unknown_device': 'Неизвестное устройство',
  'paired': 'Сопряжено',
  'not_paired': 'Не сопряжено',
  'price': 'Цена',
  'date': 'Дата',
  'ean': 'EAN',
  'sku': 'SKU',
  'size': 'Размер',
  'color': 'Цвет',
  'yes': 'Да',
  'no': 'Нет',
  'b_ware': 'B-Ware',
  'b_ware_question': 'Это товар B-Ware?',
  'b_ware_comment': 'Комментарий (необязательно)',
  'occupied_slot_options_body':
      'Складское место: {slot}\n\nИспользуйте другое место или добавьте количество в это место.',
  'existing_product_found_title': 'Найден такой же товар',
  'existing_product_found_body':
      'Такой же товар уже есть в местах: {locations}.\nНовое место: {target}.\n\nВыберите: добавить количество к существующему или создать новый товар.',
  'existing_product_slot_taken_title': 'Место на складе уже занято',
  'existing_product_slot_taken_body':
      'Место {slot} уже занято.\n\nВыберите: создать с новым номером или добавить количество к существующему товару.',
  'existing_product_create_new': 'Создать новый',
  'existing_product_add_quantity': 'Добавить количество',
  'oldest_item_date': 'Дата самого старого товара: {date}',
  'remove_fifo_hint': 'Будет удален самый старый товар (FIFO).',
};
