const Map<String, String> appLabelsEn = <String, String>{
  'login': 'Login',
  'login_title': 'Login',
  'login_subtitle': 'Secure access',
  'username': 'Login',
  'password': 'Password',
  'fingerprint_login': 'Login with fingerprint',
  'fingerprint_next': 'Use fingerprint next time',
  'fingerprint_unavailable': 'Fingerprint is not available on this device.',
  'fingerprint_reason': 'Authenticate to log in to Warehub.',
  'fingerprint_setup_canceled': 'Fingerprint setup was canceled.',
  'session_expired_login_again': 'Session expired. Login with password once.',
  'enable_fingerprint_title': 'Enable fingerprint login?',
  'enable_fingerprint_body': 'Use fingerprint for faster login next time?',
  'enable': 'Enable',
  'later': 'Later',
  'language': 'Language',
  'cancel': 'Cancel',
  'next': 'Next',
  'prev': 'Prev',
  'skip': 'Skip',
  'yes': 'Yes',
  'no': 'No',
  'save': 'Save',
  'add': 'Add',
  'remove': 'Remove',
  'print': 'Print',
  'print_now': 'Print now',
  'print_image': 'Print image',
  'printer_setup': 'Printer setup',
  'scan': 'SCAN',
  'scan_action_title': 'Scan action',
  'scan_action_subtitle': 'Choose what to do with the scanned product.',
  'scan_source_title': 'Input source',
  'scan_source_subtitle': '{action}: choose source',
  'scan_by_qr': 'Scan by QR',
  'scan_by_kid': 'Enter KID number',
  'scan_by_section_slot': 'By section + slot',
  'scan_source_empty': 'Empty product',
  'category_optional': 'Category (optional)',
  'subcategory_optional': 'Subcategory (optional)',
  'no_selection': 'No selection',
  'kid_number': 'KID number',
  'kid_required': 'KID number is required.',
  'enter_kid_for_add': 'Enter KID number for ADD',
  'enter_kid_for_remove': 'Enter KID number for REMOVE',
  'no_active_products_for_selection':
      'No active products found for selected input.',
  'no_active_products_for_location':
      'No active products found for location {location}.',
  'select_printer': 'Select printer',
  'connect': 'Connect',
  'update_available_title': 'Update available',
  'update_later': 'Later',
  'update_now': 'Update',
  'permission_dont_allow': 'Don\'t allow',
  'permission_allow': 'Allow',
  'preview_only_mode': 'Preview only mode',
  'preview_only_help': 'Show label preview and do not print.',
  'label_type': 'Label type',
  'label_type_value': 'Label type {value}',
  'density': 'Density',
  'density_value': 'Density {value}',
  'order': 'Order',
  'confirm_return': 'Confirm return',
  'warehouse_feed': 'Warehouse Feed',
  'realtime_intakes': 'Realtime intake operations',
  'units_count': 'Units  {count}',
  'no_products': 'No products in list yet.\nTap SCAN to add or remove product.',
  'logout': 'Logout',
  'account': 'Account',
  'profile': 'Profile',
  'login_value': 'Login',
  'email_value': 'Email',
  'avatar_url': 'Avatar URL',
  'api_base_url': 'API URL',
  'upload_avatar': 'Upload avatar',
  'save_profile': 'Save profile',
  'change_password': 'Change password',
  'current_password': 'Current password',
  'new_password': 'New password',
  'profile_updated': 'Profile updated.',
  'profile_update_failed': 'Profile update failed: {error}',
  'password_changed': 'Password changed.',
  'password_change_failed': 'Password change failed: {error}',
  'profile_load_failed': 'Failed to load profile: {error}',
  'api_base_saved': 'API URL saved.',
  'avatar_uploaded': 'Avatar uploaded.',
  'check_updates': 'Check updates',
  'update_available': 'Update available',
  'update_app': 'Update app',
  'printer_connected': 'Printer connected',
  'connect_printer': 'Connect printer',
  'more': 'More',
  'loading': 'Loading...',
  'sort': 'Sort',
  'newest_first': 'Newest first',
  'oldest_first': 'Oldest first',
  'search': 'Search',
  'activity': 'Activity',
  'filter_list': 'Filter list',
  'all_sections': 'All sections',
  'all_activity': 'All activity',
  'load_more': 'Load more',
  'active_filters_count': 'Filters: {count}',
  'apply': 'Apply',
  'reset': 'Reset',
  'kid': 'KID',
  'section_slot': 'Section/Slot',
  'product_key': 'Product key',
  'count': 'Count',
  'boxes': 'Boxes',
  'unit': 'Unit',
  'memo': 'Memo',
  'active': 'Active',
  'inactive': 'Inactive',
  'auto_delete_in': 'Auto-delete in {days}d',
  'auto_delete_due': 'Auto-delete due',
  'removed': 'Removed',
  'scan_qr': 'Scan QR',
  'align_qr': 'Align QR code in frame',
  'update_available_body':
      'A new app version is available.\nCurrent: {current}\nLatest: {latest}\nChannel: {channel}',
  'settings': 'Settings',
  'camera_permission_title': 'Camera permission',
  'camera_permission_body':
      'Camera is required to scan QR codes.\nPlease allow camera access.',
  'bluetooth_permission_title': 'Bluetooth permission',
  'bluetooth_permission_body':
      'Bluetooth/Nearby is required to connect the printer.\nPlease allow access.',
  'bluetooth_permission_settings':
      'Bluetooth permission was not granted. Allow Nearby devices/Bluetooth in app settings.',
  'bluetooth_disabled': 'Bluetooth is disabled.',
  'no_printers_found':
      'No bluetooth printers found. Turn on printer and try again.',
  'printer_selection_cancelled': 'Printer selection was cancelled.',
  'printer_connect_failed':
      'Failed to pair/connect printer {name} ({address}).',
  'load_list_failed_http': 'Load list failed: HTTP {code}',
  'load_list_invalid': 'Load list failed: invalid response.',
  'load_list_error': 'Load list error: {error}',
  'latest_version': 'You already have the latest version ({version}).',
  'failed_check_updates': 'Failed to check updates.',
  'update_link_missing': 'Update link is not configured.',
  'failed_open_update': 'Failed to open update link.',
  'update_started': 'Update download started.',
  'camera_permission_denied': 'Camera permission was not granted.',
  'bluetooth_permission_denied': 'Bluetooth permission was not granted.',
  'printer_connected_message': 'Printer connected.',
  'preview_only_on': 'Preview mode is ON: nothing printed.',
  'print_canceled': 'Print canceled.',
  'printed_labels': 'Printed {count} label(s) (Nimbot B1).',
  'kid_not_found': 'KID not found in QR code.',
  'photos_upload_failed': 'Photos failed to upload: {count}.',
  'photos_upload_recovered': 'Recovered photo uploads after retry: {count}.',
  'photo_upload_retry_title': 'Retry failed uploads',
  'photo_upload_retry_body':
      '{count} photo(s) still failed to upload. Retry now?',
  'retry': 'Retry',
  'order_id_missing': 'OrderID was not found in QR payload.',
  'afterbuy_unavailable': 'Afterbuy list unavailable: {error}',
  'image_printed': 'Image printed (Nimbot B1).',
  'invalid_width_height': 'Invalid width/height.',
  'print_preview': 'Print preview',
  'label_preview': 'Label preview',
  'labels_preview': 'Labels preview ({count})',
  'close': 'Close',
  'step_title': 'Step {step}/{total}',
  'number_of_boxes': 'Number of boxes',
  'warehouse_place': 'Warehouse place',
  'enter_place': 'Enter place',
  'format_place': 'Use format like 88 or 88A',
  'warehouse_place_taken':
      'This warehouse place is already in use. Enter a new one.',
  'occupied_slot_options_body':
      'Warehouse place: {slot}\n\nUse another place, or add quantity to this place.',
  'existing_product_found_title': 'Existing product found',
  'existing_product_found_body':
      'Same product already exists in: {locations}.\nNew location: {target}.\n\nChoose: add to existing quantity, or create as a new product.',
  'existing_product_slot_taken_title': 'Warehouse slot is already occupied',
  'existing_product_slot_taken_body':
      'Warehouse slot {slot} is already occupied.\n\nChoose: create with a new slot number, or add quantity to the existing product.',
  'existing_product_create_new': 'Create new',
  'existing_product_add_quantity': 'Add quantity',
  'take_photos_question': 'Take product photos? Up to 10 photos.',
  'take_photos': 'Take photos',
  'skip_photos': 'Skip photos',
  'photo_title': 'Photo {current}/{total}',
  'add_one_more_photo': 'Add one more photo?',
  'add_photo': 'Add photo',
  'continue': 'Continue',
  'ordered_items': 'Ordered items (Afterbuy):',
  'no_structured_items': 'No structured items parsed from Afterbuy page.',
  'mark_as_returned': 'Mark as returned:',
  'na': 'n/a',
  'scan_action_help': 'Choose what to do with the scanned product.',
  'print_image_title': 'Print image',
  'print_image_source_title': 'Image source',
  'gallery': 'Gallery',
  'manual': 'Manual',
  'printer_setup_saved':
      'Printer setup saved: {width}x{height}, type {type}, density {density}, preview-only {preview}.',
  'printer_hint': 'For this B1/T50 setup use 384x640, label type 1, density 5.',
  'parts_quantity_title': 'Parts quantity',
  'parts_quantity_help': 'Enter how many parts this product has.',
  'parts_label': 'Parts',
  'quantity_min_error': 'Quantity must be greater than 0.',
  'enter_number_min': 'Enter a number >= {min}',
  'item_added': 'Item added: {location}, boxes: {boxes}.',
  'error_kid_missing': 'KID is missing in QR payload.',
  'error_qr_required': 'QR code is required.',
  'create_intake_failed_unauthorized':
      'Create intake failed: HTTP 401 unauthorized',
  'create_intake_failed_http': 'Create intake failed: HTTP {code}',
  'create_intake_failed_http_with_details':
      'Create intake failed: HTTP {code}. {details}',
  'create_intake_failed_duplicate':
      'This product is already in the intake list for the same unit/box.',
  'create_intake_response_invalid': 'Create intake response is not an object.',
  'delete_intake_failed_unauthorized':
      'Delete intake failed: HTTP 401 unauthorized',
  'delete_intake_failed_http': 'Delete intake failed: HTTP {code}',
  'no_active_products':
      'No active products found in local list for OrderID {order}.',
  'returned_marked': 'Returned: {count} part(s) marked as removed.',
  'oldest_item_date': 'Oldest item date: {date}',
  'remove_fifo_hint': 'Will remove the oldest item (FIFO).',
  'label_width': 'Label width (px)',
  'label_height': 'Label height (px)',
  'on': 'on',
  'off': 'off',
  'unknown_device': 'Unknown device',
  'paired': 'Paired',
  'not_paired': 'Not paired',
  'price': 'Price',
  'date': 'Date',
  'ean': 'EAN',
  'sku': 'SKU',
  'size': 'Size',
  'color': 'Color',
  'b_ware': 'B-Ware',
  'b_ware_question': 'Is this a B-Ware product?',
  'b_ware_comment': 'Comment (optional)',
};
