const Map<String, String> appLabelsRu = <String, String>{
  'login': 'Вход',
  'login_title': 'Вход',
  'login_subtitle': 'Безопасный доступ',
  'username': 'Логин',
  'password': 'Пароль',
  'forgot_password': 'Забыли пароль?',
  'reset_password_title': 'Восстановление пароля',
  'reset_email_help': 'Введите email, чтобы получить код восстановления.',
  'reset_code_help': 'Введите 6-значный код из письма.',
  'reset_password_help': 'Создайте новый пароль для аккаунта.',
  'send_reset_code': 'Отправить код',
  'reset_code': 'Код восстановления',
  'update_password': 'Обновить пароль',
  'reset_code_sent': 'Если email существует, код восстановления отправлен.',
  'password_reset_success': 'Пароль сброшен. Теперь можно войти.',
  'reset_email_invalid': 'Введите корректный email.',
  'reset_code_invalid': 'Код должен состоять из 6 цифр.',
  'reset_password_mismatch': 'Подтверждение пароля не совпадает.',
  'reset_password_length': 'Пароль должен быть от 8 до 128 символов.',
  'reset_password_requirements':
      'Пароль должен содержать заглавную букву, строчную букву и цифру.',
  'reset_request_failed': 'Не удалось отправить код восстановления.',
  'reset_confirm_failed': 'Не удалось сбросить пароль.',
  'session_expired_login_again': 'Сессия истекла. Войдите один раз по паролю.',
  'language': 'Язык',
  'warehouse_map': 'Карта склада',
  'warehouse_map_subtitle': 'Схема склада и расположение товаров',
  'warehouse_map_hint': 'Разведите пальцы для масштаба и перетаскивайте карту.',
  'warehouse_map_semantics':
      'Карта склада с шоурумом в зоне A, зонами до M и зоной приёмки товаров.',
  'warehouse_showroom': 'ШОУРУМ',
  'warehouse_map_zoom_in': 'Приблизить',
  'warehouse_map_zoom_out': 'Отдалить',
  'cancel': 'Отмена',
  'next': 'Далее',
  'prev': 'Назад',
  'skip': 'Пропустить',
  'save': 'Сохранить',
  'add': 'Добавить',
  'remove': 'Удалить',
  'return_to_stock': 'Вернуть на склад',
  'confirm_return_to_stock': 'Отметить {location} как возвращённый на склад?',
  'confirm_remove_location':
      'Удалить самый старый активный товар с места {location}?',
  'return_marked': 'Отмечено {count} шт. как возвращённые на склад.',
  'print': 'Печать',
  'print_now': 'Печатать',
  'print_image': 'Печать изображения',
  'printer_setup': 'Настройка принтера',
  'printer_actions': 'Действия принтера',
  'products_tab': 'Товары',
  'product_details': 'Детали товара',
  'product_information': 'Информация о товаре',
  'warehouse_locations': 'Места на складе',
  'scan': 'SCAN',
  'scan_action_title': 'Действие сканирования',
  'scan_action_subtitle': 'Выберите действие для отсканированного товара.',
  'scan_source_title': 'Источник ввода',
  'scan_source_subtitle': '{action}: выберите источник',
  'scan_by_qr': 'Сканировать QR',
  'scan_by_kid': 'Ввести KID номер',
  'scan_by_section_slot': 'По секции и месту',
  'scan_source_empty': 'Пустой товар',
  'category_optional': 'Категория (необязательно)',
  'subcategory_optional': 'Подкатегория (необязательно)',
  'no_selection': 'Без выбора',
  'kid_number': 'KID номер',
  'kid_required': 'KID номер обязателен.',
  'enter_kid_for_add': 'Введите KID номер для ADD',
  'enter_kid_for_remove': 'Введите KID номер для REMOVE',
  'no_active_products_for_selection':
      'Нет активных товаров для выбранного ввода.',
  'no_active_products_for_location':
      'Нет активных товаров для места {location}.',
  'select_printer': 'Выберите принтер',
  'connect': 'Подключить',
  'update_available_title': 'Доступно обновление',
  'update_later': 'Позже',
  'update_now': 'Обновить',
  'permission_dont_allow': 'Не разрешать',
  'permission_allow': 'Разрешить',
  'preview_only_mode': 'Только предпросмотр',
  'preview_only_help': 'Показывать предпросмотр и не печатать.',
  'label_type': 'Тип этикетки',
  'label_type_value': 'Тип этикетки {value}',
  'label_layout': 'Макет этикетки',
  'label_layout_main': 'Основной',
  'label_layout_parts': 'Части',
  'label_layout_size': 'Размер',
  'label_layout_move': 'Сдвиг',
  'label_layout_decrease': 'Уменьшить',
  'label_layout_increase': 'Увеличить',
  'label_layout_left': 'Влево',
  'label_layout_up': 'Вверх',
  'label_layout_down': 'Вниз',
  'label_layout_right': 'Вправо',
  'label_layout_reset_defaults': 'Сбросить настройки',
  'label_layout_saved': 'Макет этикетки сохранён для всех пользователей.',
  'label_layout_sync_failed':
      'Сохранено локально, но не удалось синхронизировать общий макет.',
  'density': 'Плотность',
  'density_value': 'Плотность {value}',
  'order': 'Заказ',
  'confirm_return': 'Подтвердить возврат',
  'warehouse_feed': 'Лента склада',
  'realtime_intakes': 'Операции приемки в реальном времени',
  'no_products':
      'Пока нет товаров в списке.\nНажмите SCAN, чтобы добавить или удалить товар.',
  'logout': 'Выйти',
  'account': 'Аккаунт',
  'profile': 'Профиль',
  'login_value': 'Логин',
  'email_value': 'Электронная почта',
  'first_name': 'Имя',
  'last_name': 'Фамилия',
  'phone_number': 'Телефон',
  'profile_status': 'Статус',
  'profile_role': 'Роль',
  'profile_user': 'Пользователь',
  'profile_username': 'Имя пользователя',
  'profile_role_admin': 'Администратор',
  'profile_role_user': 'Пользователь',
  'profile_status_pending': 'На рассмотрении',
  'profile_status_approved': 'Подтверждён',
  'profile_status_rejected': 'Отклонён',
  'profile_status_unknown': 'Неизвестно',
  'avatar_url': 'Аватар',
  'api_base_url': 'URL API',
  'upload_avatar': 'Загрузить аватар',
  'save_profile': 'Сохранить профиль',
  'change_password': 'Сменить пароль',
  'current_password': 'Текущий пароль',
  'new_password': 'Новый пароль',
  'confirm_password': 'Повторите пароль',
  'profile_updated': 'Профиль обновлён.',
  'profile_update_failed': 'Не удалось обновить профиль: {error}',
  'password_changed': 'Пароль изменён.',
  'password_change_failed': 'Не удалось изменить пароль: {error}',
  'profile_load_failed': 'Не удалось загрузить профиль: {error}',
  'api_base_saved': 'API URL сохранён.',
  'avatar_uploaded': 'Аватар загружен.',
  'check_updates': 'Проверить обновления',
  'update_available': 'Обновление доступно',
  'update_app': 'Обновить приложение',
  'printer_connected': 'Принтер подключен',
  'connect_printer': 'Подключить принтер',
  'more': 'Ещё',
  'loading': 'Загрузка...',
  'opening_app': 'Открываем приложение...',
  'sort': 'Сортировка',
  'newest_first': 'Сначала новые',
  'oldest_first': 'Сначала старые',
  'search': 'Поиск',
  'activity': 'Активность',
  'filter_list': 'Фильтр списка',
  'load_filters_failed': 'Не удалось загрузить варианты фильтров: {error}',
  'filter_place': 'Место',
  'all_places': 'Все места',
  'inventory_search_loading_hint': 'Искать товары',
  'inventory_search_hint': 'Искать среди {count} товаров',
  'filter_section': 'Секция',
  'filter_destination': 'Размещение',
  'filter_status': 'Статус',
  'all_destinations': 'Все',
  'warehouse': 'Склад',
  'store': 'Магазин',
  'b_ware_only': 'Только уценённые товары',
  'in_transit_only': 'Только товары в пути',
  'all_sections': 'Все секции',
  'filter_quantity': 'Количество',
  'all_quantities': 'Любое количество',
  'filter_room': 'Комната',
  'all_rooms': 'Все комнаты',
  'filter_type': 'Тип',
  'all_types': 'Все типы',
  'filter_company': 'Компания',
  'all_companies': 'Все компании',
  'filter_color': 'Цвет',
  'all_colors': 'Все цвета',
  'filter_material': 'Материал',
  'all_materials': 'Все материалы',
  'all_activity': 'Вся активность',
  'load_more': 'Загрузить ещё',
  'active_filters_count': 'Фильтры: {count}',
  'apply': 'Применить',
  'reset': 'Сбросить',
  'kid': 'KID',
  'section_slot': 'Секция/Слот',
  'product_key': 'Компания',
  'pallet_placeholder': 'Палеты',
  'count': 'Количество',
  'boxes': 'Коробки',
  'unit': 'Единица',
  'memo': 'Примечание',
  'active': 'Активный',
  'inactive': 'Неактивный',
  'auto_delete_in': 'Авто-удаление через {days} дн.',
  'auto_delete_due': 'Авто-удаление просрочено',
  'removed': 'Удалён',
  'scan_qr': 'Сканировать QR',
  'align_qr': 'Наведите QR-код в рамку',
  'update_available_body':
      'Доступна новая версия приложения.\nТекущая: {current}\nНовая: {latest}\nКанал: {channel}',
  'settings': 'Настройки',
  'camera_permission_title': 'Разрешение на камеру',
  'camera_permission_body':
      'Камера нужна для сканирования QR-кодов.\nПожалуйста, разрешите доступ.',
  'bluetooth_permission_title': 'Разрешение Bluetooth',
  'bluetooth_permission_body':
      'Bluetooth/Nearby нужен для подключения принтера.\nПожалуйста, разрешите доступ.',
  'bluetooth_permission_settings':
      'Разрешение Bluetooth не выдано. Разрешите доступ в настройках.',
  'bluetooth_disabled': 'Bluetooth отключён.',
  'no_printers_found':
      'Bluetooth-принтеры не найдены. Включите принтер и повторите попытку.',
  'printer_selection_cancelled': 'Выбор принтера отменён.',
  'printer_connect_failed':
      'Не удалось подключить принтер: {name} ({address}).',
  'load_list_failed_http': 'Ошибка загрузки списка: HTTP {code}',
  'load_list_invalid': 'Ошибка загрузки списка: некорректный ответ.',
  'load_list_error': 'Ошибка загрузки списка: {error}',
  'network_unavailable':
      'Нет подключения к интернету. Сервер сейчас недоступен.',
  'network_unavailable_load':
      'Нет подключения к интернету. Сейчас невозможно загрузить список.',
  'network_unavailable_login':
      'Нет подключения к интернету. Сейчас невозможно выполнить вход.',
  'action_failed_error': 'Действие не выполнено: {error}',
  'login_failed_error': 'Ошибка входа: {error}',
  'latest_version': 'У вас уже последняя версия ({version}).',
  'failed_check_updates': 'Не удалось проверить обновления.',
  'update_link_missing': 'Ссылка на обновление не настроена.',
  'failed_open_update': 'Не удалось открыть ссылку обновления.',
  'update_started': 'Загрузка обновления началась.',
  'camera_permission_denied': 'Разрешение на камеру не выдано.',
  'bluetooth_permission_denied': 'Разрешение Bluetooth не выдано.',
  'printer_connected_message': 'Принтер подключён.',
  'preview_only_on': 'Включён предпросмотр: печать не выполнена.',
  'print_canceled': 'Печать отменена.',
  'printed_labels': 'Напечатано {count} этикеток (Nimbot B1).',
  'kid_not_found': 'KID не найден в QR-коде.',
  'photos_upload_failed': 'Не удалось загрузить фото: {count}.',
  'photos_upload_recovered':
      'Успешно загружено после повторной попытки: {count}.',
  'photo_upload_retry_title': 'Повторить загрузку фото',
  'photo_upload_retry_body':
      'Не удалось загрузить фото: {count}. Повторить сейчас?',
  'retry': 'Повторить',
  'order_id_missing': 'OrderID не найден в QR-коде.',
  'afterbuy_unavailable': 'Afterbuy недоступен: {error}',
  'image_printed': 'Изображение напечатано (Nimbot B1).',
  'invalid_width_height': 'Неверная ширина/высота.',
  'print_preview': 'Предпросмотр печати',
  'label_preview': 'Предпросмотр этикетки',
  'labels_preview': 'Предпросмотр этикеток ({count})',
  'close': 'Закрыть',
  'step_title': 'Шаг {step}/{total}',
  'number_of_boxes': 'Количество коробок',
  'location': 'Локация',
  'store_destination_store': 'Магазин',
  'store_destination_warehouse': 'Склад',
  'warehouse_place': 'Место на складе',
  'enter_place': 'Введите место',
  'format_place': 'Используйте формат 88 или 88A',
  'warehouse_place_taken': 'Это место на складе уже занято. Введите новое.',
  'take_photos_question': 'Сделать фото товара? До 10 фото.',
  'take_photos': 'Сделать фото',
  'skip_photos': 'Пропустить фото',
  'photo_title': 'Фото {current}/{total}',
  'add_one_more_photo': 'Добавить ещё одно фото?',
  'add_photo': 'Добавить фото',
  'add_photos': 'Добавить фото',
  'photos_added': 'Добавлено {count} фото.',
  'photos_limit_reached': 'У этого товара уже максимум 10 фото.',
  'continue': 'Продолжить',
  'ordered_items': 'Заказанные товары (Afterbuy):',
  'no_structured_items': 'Структурированные товары из Afterbuy не найдены.',
  'mark_as_returned': 'Отметить как возвращённые:',
  'na': 'н/д',
  'scan_action_help': 'Выберите действие для отсканированного товара.',
  'print_image_title': 'Печать изображения',
  'print_image_source_title': 'Источник изображения',
  'gallery': 'Галерея',
  'manual': 'Manual',
  'printer_setup_saved':
      'Принтер сохранён: {width}x{height}, тип {type}, плотность {density}, предпросмотр {preview}.',
  'printer_hint':
      'Для вашего B1/T50 используйте 384x640, тип этикетки 1, плотность 5.',
  'parts_quantity_title': 'Количество частей',
  'parts_quantity_help': 'Введите количество частей этого товара.',
  'parts_label': 'Части',
  'quantity_min_error': 'Количество должно быть больше 0.',
  'enter_number_min': 'Введите число >= {min}',
  'enter_number_range': 'Введите число от {min} до {max}.',
  'item_added': 'Товар добавлен: {location}, коробок: {boxes}.',
  'error_kid_missing': 'KID отсутствует в QR-данных.',
  'error_qr_required': 'QR-код обязателен.',
  'create_intake_failed_unauthorized': 'Ошибка создания: HTTP 401 unauthorized',
  'create_intake_failed_http': 'Ошибка создания: HTTP {code}',
  'create_intake_failed_http_with_details':
      'Ошибка создания: HTTP {code}. {details}',
  'create_intake_failed_duplicate':
      'Товар уже есть в списке приемки для той же единицы/коробки.',
  'create_intake_response_invalid': 'Ответ create intake не объект.',
  'delete_intake_failed_unauthorized': 'Ошибка удаления: HTTP 401 unauthorized',
  'delete_intake_failed_http': 'Ошибка удаления: HTTP {code}',
  'no_active_products':
      'Нет активных товаров в локальном списке для OrderID {order}.',
  'returned_marked': 'Возврат: отмечено удалёнными частей: {count}.',
  'label_width': 'Ширина этикетки (px)',
  'label_height': 'Высота этикетки (px)',
  'on': 'вкл',
  'off': 'выкл',
  'unknown_device': 'Неизвестное устройство',
  'paired': 'Сопряжено',
  'not_paired': 'Не сопряжено',
  'price': 'Цена',
  'date': 'Дата',
  'ean': 'EAN',
  'sku': 'SKU',
  'size': 'Размер',
  'color': 'Цвет',
  'color_schwarz': 'Черный',
  'color_weiss': 'Белый',
  'color_grau': 'Серый',
  'color_silber': 'Серебристый',
  'color_beige': 'Бежевый',
  'color_braun': 'Коричневый',
  'color_blau': 'Синий',
  'color_hellblau': 'Голубой',
  'color_marineblau': 'Темно-синий',
  'color_turkis': 'Бирюзовый',
  'color_grun': 'Зеленый',
  'color_hellgrun': 'Светло-зеленый',
  'color_gelb': 'Желтый',
  'color_orange': 'Оранжевый',
  'color_rot': 'Красный',
  'color_bordeaux': 'Бордовый',
  'color_rosa': 'Розовый',
  'color_lila': 'Лиловый',
  'color_violett': 'Фиолетовый',
  'color_mehrfarbig': 'Многоцветный',
  'yes': 'Да',
  'no': 'Нет',
  'b_ware': 'Уценённый товар',
  'b_ware_question': 'Это уценённый товар?',
  'b_ware_comment': 'Комментарий (необязательно)',
  'in_transit': 'В пути',
  'in_transit_question': 'Этот товар находится в пути?',
  'occupied_slot_options_body':
      'Складское место: {slot}\n\nИспользуйте другое место или добавьте количество в это место.',
  'existing_product_found_title': 'Найден такой же товар',
  'existing_product_found_body':
      'Такой же товар уже есть в местах: {locations}.\nНовое место: {target}.\n\nВыберите: добавить количество к существующему или создать новый товар.',
  'existing_product_slot_taken_title': 'Место на складе уже занято',
  'existing_product_slot_taken_body':
      'Место {slot} уже занято.\n\nВыберите: создать с новым номером или добавить количество к существующему товару.',
  'existing_product_create_new': 'Создать новый',
  'existing_product_add_quantity': 'Добавить количество',
  'oldest_item_date': 'Дата самого старого товара: {date}',
  'remove_fifo_hint': 'Будет удален самый старый товар (FIFO).',
};
