# Generated by Django 5.2.14 on 2026-07-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_service', '0004_telegramaccessbinding_app_user_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramconversationstate',
            name='state',
            field=models.CharField(choices=[('idle', 'idle'), ('awaiting_access_email', 'awaiting_access_email'), ('awaiting_action', 'awaiting_action'), ('awaiting_kid', 'awaiting_kid'), ('awaiting_list_form', 'awaiting_list_form'), ('awaiting_place', 'awaiting_place'), ('awaiting_main_ean', 'awaiting_main_ean'), ('awaiting_quantity', 'awaiting_quantity'), ('awaiting_price', 'awaiting_price'), ('awaiting_confirmation', 'awaiting_confirmation'), ('processing', 'processing'), ('completed', 'completed'), ('cancelled', 'cancelled')], db_index=True, default='idle', max_length=64),
        ),
    ]
