# Generated by Django 5.2.15 on 2026-06-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='importedproduct',
            name='uniq_imported_product_site_site_key_ean',
        ),
        migrations.AddConstraint(
            model_name='importedproduct',
            constraint=models.UniqueConstraint(condition=models.Q(('source_model__gt', '')), fields=('site', 'site_key', 'source_model'), name='uniq_imported_product_site_site_key_source_model'),
        ),
    ]
