# Generated by Django 5.2.15 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog_core", "0003_remove_importedproduct_uniq_imported_product_site_site_key_ean_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="importedproduct",
            name="source_ean_field",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
