"""
Django settings for database_service project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from urllib.parse import urlparse, unquote
from pathlib import Path
from dotenv import load_dotenv
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
WORKSPACE_ROOT = BASE_DIR.parent.parent.parent
REPO_ROOT = WORKSPACE_ROOT
for env_path in (
    REPO_ROOT / ".env",
    REPO_ROOT / "infra" / ".env",
    BASE_DIR / ".env",
):
    if env_path.is_file():
        load_dotenv(env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-s@#b7z^&ktmvmezo9%70rme!*bn#@mq78-kz+u#si*w5r#r&hc')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'true').lower() == 'true'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'catalog_core',
    'database',
    'orders_pars',
    'otto_service',
    'hood_service',
    'jv_services',
    'xl_services',
    'kaufland',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'database_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'database_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
def _db_config_from_url(raw_url: str):
    try:
        parsed = urlparse(raw_url)
    except Exception:
        return None

    scheme = (parsed.scheme or "").lower()
    if scheme not in {"postgres", "postgresql"}:
        return None

    db_name = (parsed.path or "").lstrip("/")
    if not db_name:
        return None

    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": unquote(db_name),
        "USER": unquote(parsed.username or ""),
        "PASSWORD": unquote(parsed.password or ""),
        "HOST": parsed.hostname or "127.0.0.1",
        "PORT": str(parsed.port or 5432),
    }


# Priority:
# 1) POSTGRES_* variables when WAREHUB_LOCAL_DEV_ROOT_ENV_ACTIVE=true
# 2) DATABASE_URL (postgres://... or postgresql://...)
# 3) POSTGRES_* variables
# 4) sqlite for local quick start
_local_root_env_active = (os.getenv("WAREHUB_LOCAL_DEV_ROOT_ENV_ACTIVE", "false") or "").strip().lower() in {
    "1", "true", "yes", "on"
}
_database_url = (os.getenv("DATABASE_URL") or "").strip()
_database_url_config = _db_config_from_url(_database_url) if _database_url else None

if _local_root_env_active and os.getenv('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'sofortbot'),
            'USER': os.getenv('POSTGRES_USER', 'sofortbot'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'sofortbot'),
            'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.getenv('POSTGRES_PORT', '8933'),
        }
    }
elif _database_url_config:
    DATABASES = {"default": _database_url_config}
elif os.getenv('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', 'sofortbot'),
            'USER': os.getenv('POSTGRES_USER', 'sofortbot'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'sofortbot'),
            'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.getenv('POSTGRES_PORT', '8933'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Optional external EAN mapping database.
# Priority:
# 1) EAN_MAP_DATABASE_URL
# 2) derive from DATABASE_URL by switching DB name to `sofortbot_ean_map`
_ean_map_database_url = (os.getenv("EAN_MAP_DATABASE_URL") or "").strip()
_ean_map_database_config = _db_config_from_url(_ean_map_database_url) if _ean_map_database_url else None

if _ean_map_database_config:
    DATABASES["ean_map"] = _ean_map_database_config
elif _database_url_config:
    _derived_ean_map = dict(_database_url_config)
    _derived_ean_map["NAME"] = os.getenv("EAN_MAP_DATABASE_NAME", "sofortbot_ean_map")
    DATABASES["ean_map"] = _derived_ean_map


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS/CSRF for frontend apps (dev/stage/prod)
_cors_allowed_origins_env = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:8931,http://127.0.0.1:8931,https://stagewarehub.automatonsoft.de,https://warehub.automatonsoft.de'
)
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_allowed_origins_env.split(',') if o.strip()]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    'x-request-id',
]

_csrf_trusted_origins_env = os.getenv(
    'CSRF_TRUSTED_ORIGINS',
    'http://localhost:8931,http://127.0.0.1:8931,https://stagewarehub.automatonsoft.de,https://warehub.automatonsoft.de'
)
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_trusted_origins_env.split(',') if o.strip()]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.openapi.AutoSchema',
}

BACKEND_AUTH_BASE_URL = (os.getenv("BACKEND_AUTH_BASE_URL") or "http://127.0.0.1:8932/api/v1").rstrip("/")
BACKEND_SESSION_BRIDGE_ALLOWED_HOSTS = [
    h.strip().lower()
    for h in os.getenv("BACKEND_SESSION_BRIDGE_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]
ORCHESTRATOR_SERVICE_AUTH_TOKEN = (os.getenv("ORCHESTRATOR_SERVICE_AUTH_TOKEN") or "").strip()
ORCHESTRATOR_SERVICE_ALLOWED_HOSTS = [
    h.strip().lower()
    for h in os.getenv("ORCHESTRATOR_SERVICE_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]
