CREATE TABLE IF NOT EXISTS label_layout_settings (
  id BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (id = TRUE),
  qr_scale DOUBLE PRECISION NOT NULL DEFAULT 0.78,
  qr_offset_x DOUBLE PRECISION NOT NULL DEFAULT 0,
  qr_offset_y DOUBLE PRECISION NOT NULL DEFAULT 0,
  main_scale DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  main_offset_x DOUBLE PRECISION NOT NULL DEFAULT 0,
  main_offset_y DOUBLE PRECISION NOT NULL DEFAULT 0,
  parts_scale DOUBLE PRECISION NOT NULL DEFAULT 1.0,
  parts_offset_x DOUBLE PRECISION NOT NULL DEFAULT 0,
  parts_offset_y DOUBLE PRECISION NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
